### ISSUE TITLE
http://web.fluffi:8880/systems/removeDevSystem/{{system}}/ returns 404

### ISSUE THREAD

**Issue by maverickwoo** [siemens/fluffi#101]
To reproduce, visit http://web.fluffi:8880/systems, then:

1. Create a runner system using the web interface. For this example, say the system name is `fluffi-0228-Linux3`.

2. Click on the X icon at the end of the row of the newly-created system. The browser will visit http://web.fluffi:8880/systems/removeDevSystem/fluffi-0228-Linux3/ and get a 404.

**Comment by p4cx** [comment]
Depends on #102
