### ISSUE TITLE
Evaluate the decision to prepend "dev-" to runner systems created using web interface

### ISSUE THREAD

**Issue by maverickwoo** [siemens/fluffi#102]
With current [master](https://github.com/siemens/fluffi/tree/ab9b81fad21adf2a0377665e6f6a3648403e84fc), a runner system created using the web interface has two "names" that spell differently. Say I have just created a system called `fluffi-0228-Linux3` using the web interface.

1. In http://web.fluffi:8880/systems, we see a new table row with link `fluffi-0228-Linux3` in the browser. But the target of that link is `http://web.fluffi:8880/systems/view/dev-fluffi-0228-Linux3/linux`.
2. In http://pole.fluffi:8888/#/host, we see a new host with name `dev-fluffi-0228-Linux3`, but with the Ansible variable `ansible_ssh_host` set to `fluffi-0228-Linux3.fluffi`.
3. In MariaDB `systems` table, the `Name` column of the new row is `dev-fluffi-0228-Linux3`.

This design can be quite confusing to starters and basically require manual editing of the DB content.

Moreover, if we restart the containers (without any modification to the file system or DB content), `fluffi-0228-Linux3` won't show up in http://web.fluffi:8880/systems any more because of its "dev-" prefix in the DB. However, adding `fluffi-0228-Linux3` again would not work and would result in the error message:
> Error adding new system! System already exists (or check database)!

This issue is related to #98.

**Comment by TomSie** [comment]
I favor the idea of getting rid of the "dev-" systems. Imho all systems should be treated equally, if possible.

However, we need to review the code to see what breaks if we remove this.

**Comment by p4cx** [comment]
I agree with you here and I will review and remove `dev-` (if possible). In addition, every system should be removable in the web gui and not just `dev-` systems.

**Comment by maverickwoo** [comment]
Personally, I also favor a design that
1. treats every host equally, 
2. sees the web interface as the GUI method of performing CRUD in the DB, and 
3. sees the DB as the single source of truth of the inventory of runner systems.

In this design, the Ansible inventory specification will follow a common pattern for cloud applications: a [dynamic inventory](https://docs.ansible.com/ansible/latest/dev_guide/developing_inventory.html), overlayed with overrides through the file system if necessary. (In older designs, adding overrides through the file system is often necessary due to schema inflexibility; nowadays we can use a JSON column to allow pretty much any overrides.)

P.S. Speaking of Ansible inventory, I suggest favoring YAML over INI, even for human-written files. When an inventory have enough number of subgroups, editing the INI will become quite difficult.

**Comment by p4cx** [comment]
> * treats every host equally,
> * sees the web interface as the GUI method of performing CRUD in the DB, and

These two ideas for the design are now implemented in #107 

We have decided that Polemarch's host file is our source of truth. After launching the web user interface, a function is called in which the systems are retrieved from Polemarch and added to the database after you have added a location. At runtime, you can delete any system, add new systems, change locations, ...
If you restart the Webui, everything is deleted from the database that is not declared in the host file. When declared, it is added to the database.
