### ISSUE TITLE
Prerequisites needs more info

### ISSUE THREAD

**Issue by joyride9999** [siemens/fluffi#112]
Would be nice if in prerequisites is enumerated everything that is needed for building to eliminate wait time for rebuilding in case something went wrong or is not installed.
E.g. :
- VS2017 with v141 build tools
- Go with https://github.com/go-sql-driver/mysql  driver
- Cygwin with needed packages (make, cmake, gcc-*,mingw64-i686-*, mingw64-x86_64-*)
- Perl

**Comment by TomSie** [comment]
Afaik, in order to build FLUFFI on windows we need

- git
- Build tools for Visual Studio 2017 or Visual Studio 2017
- cmake
- perl (e.g. Strawberry Perl for Windows)
- cygwin64 with make, gcc-i68, and gcc installed
- go (never than 1.12) with https://github.com/go-sql-driver/mysql driver

Furthermore, to deploy to FLUFFI FTP, one also needs
- 7zip
- Winscp

**Comment by p0wer0xff** [comment]
I'm currently going through the step by step startup instructions and will refactor them as I go.

You can get the WIP on the [refactoring branch](https://github.com/siemens/fluffi/tree/refactor-deployment-and-doc) - I just included these dependencies there.

**Comment by joyride9999** [comment]
On ubuntu needs also:
sudo apt-get install flex bison

**Comment by p0wer0xff** [comment]
I noticed the qemu build trying to call these components, but they are not installed in our build environment and qemu compiles just fine nonetheless. Could you check if having them installed has any adverse effects? Like for example drastically increased build times or errors applying the qemu fluffi patch...

**Comment by joyride9999** [comment]
Also on ubuntu needs to install also smbclient.

Regarding flex and bison, for sure it will take longer ... though if they are not used maybe there is a way not to call at all those components

**Comment by p0wer0xff** [comment]
please use a separate issue for other missing dependencies. where did you see smbclient missing?

**Comment by joyride9999** [comment]
In usage section, there is :
"smbclient '//smb.fluffi/install' -c 'cd initial; get MAC2Host.csv; get initialConfiguration.sh' -U"

At least on ubuntu18.04 desktop, this is not installed by default ... anyway because of the ip changing, and dns resolving stuff by the time i arrived to this part the machine had no internet so had to remake it again with inet :)
