### ISSUE TITLE
ubuntu build error paths!?

### ISSUE THREAD

**Issue by joyride9999** [siemens/fluffi#115]
Running ./buildAll.sh -PREPARE_ENV=TRUE WITH_DEPS=TRUE i get the error:

cp: cannot stat '/fluffi/dependencies/qemu/Intel80386/qemu-arm': No such file or directory
make[1]: *** [depcopy] Error 1
make: *** [deps] Error 2

Dependencies folder has the parent "core" folder!
Also does the git clone needs to be done on the root folder "/" or it should support relative paths?

**Comment by p0wer0xff** [comment]
If you are running on the current master branch, this is most likely an issue with the make -j parameter on low powered hardware, see the [pending fix](https://github.com/siemens/fluffi/commit/016d27af9a1c185704a974f0040b087ff6751c30). 

The path you see in the error message is a path inside the [build container](https://github.com/siemens/fluffi/blob/master/build/ubuntu_based/buildAll.sh#L60) (note, the volume mount), hence the missing `core` and FLUFFI starting in the root directory.
