### ISSUE TITLE
Configure Instances Tab in Linux group doesn't work

### ISSUE THREAD

**Issue by vinamrabhatia** [siemens/fluffi#117]
With the master at following [commit](https://github.com/siemens/fluffi/tree/434131627a901e9503d365e704a7d963516c168d), http://web.fluffi:8880/systems shows multiple groups: windows, linux and odroids.

On going to [Linux group](http://web.fluffi:8880/systems/view/linux/linux), we have 4 options. 
The current state of the system is not reflected in 4] `Configure Instances`. There were some active fuzzjobs, each with a few TG, TR and TE, but the configurations shows 0 for each of them.

Besides, on changing the number of TG, TR and TE for a fuzzjob, an error pop-up box is displayed with the message "Error: Could not configure Instances!"
The terminal output at the time is the following:

> fluffiweb_1  | 'NoneType' object has no attribute 'ID'                                                    
fluffiweb_1  | [pid: 16|app: 0|req: 153/226] 10.180.62.198 () {50 vars in 1150 bytes} [Thu Mar 19 11:54:4$
 2020] POST /systems/configureSystemInstances/linux => generated 223 bytes in 6 msecs (HTTP/1.1 302) 5 hea
ders in 377 bytes (1 switches on core 0)                                                                  
fluffiweb_1  | 10.180.62.198 - - [19/Mar/2020:11:54:40 -0400] "POST /systems/configureSystemInstances/linu
x HTTP/1.1" 302 223 "http://web.fluffi:8880/systems/view/linux/linux" "Mozilla/5.0 (X11; Ubuntu; Linux x86
_64; rv:74.0) Gecko/20100101 Firefox/74.0" "-"   
fluffiweb_1  | [pid: 16|app: 0|req: 154/227] 10.180.62.198 () {44 vars in 911 bytes} [Thu Mar 19 11:54:41
2020] GET /systems => generated 20860 bytes in 549 msecs (HTTP/1.1 200) 4 headers in 247 bytes (1 switches
 on core 0)
fluffiweb_1  | 10.180.62.198 - - [19/Mar/2020:11:54:41 -0400] "GET /systems HTTP/1.1" 200 20860 "http://we
b.fluffi:8880/systems/view/linux/linux" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 F
irefox/74.0" "-"

**Comment by p4cx** [comment]
Thank you for reporting this error. It should not be possible to start agents in a group (here Linux). Agents (TG, TR and TE) can only be started on systems in a group.
