### ISSUE TITLE
running in a vbox problems

### ISSUE THREAD

**Issue by joyride9999** [siemens/fluffi#120]
- dns does not seem to work, as i cant access using names .. probably configurion is wrong
- trying to access localhost:8880 gives nginx error 
![VirtualBox_ubuntu18 04_24_03_2020_17_11_58](https://user-images.githubusercontent.com/26308356/77442250-f8172100-6df2-11ea-8a0b-a66d70c98725.png)

Vbox machine is ubuntu 18.04, static ip set to 10.66.0.1

**Comment by joyride9999** [comment]
Ubuntu 18.04 is using network-manager (https://help.ubuntu.com/community/NetworkManager)
So instead of "systemctl stop systemd-resolved.service"  should have "systemctl stop network-manager".

**Comment by p0wer0xff** [comment]
this is probably a network configuration issue.
please retry using the new and updated instructions from d492552c1db5fb3e96db9e740a770cb91aff6761 on the [refactoring branch](https://github.com/siemens/fluffi/tree/refactor-deployment-and-doc). 
There you will also find [instructions](https://github.com/siemens/fluffi/blame/refactor-deployment-and-doc/getting_started.md#L143) to change from networkmanager to networkd, which are only necessary if you are using an ubuntu desktop version - ubuntu server/headless is already configured to use networkd.
