### ISSUE TITLE
Usage documentation unclear

### ISSUE THREAD

**Issue by joyride9999** [siemens/fluffi#122]
I set up the initial machine in vbox with 10.66.0.1 ip. Compiled everything and docker is running as i can access the web server through http://web.fluffi:8880/
Added a second machine vbox machine to the network with ip 10.66.0.2

Both machine can communicate with each other .. as from the second machine i can ping gm.fluffi and get a response.
(ps : seems that also on the second machine i needed to edit resolv.conf and also stop network-manager service  for this to work)

- My understanding is that point 1) from the usage section refers to commands that should be done on the second machine, except the editing of the hosts file. Is this correct?
- as i am not familiar with ansible , an example will help in editing the host file. I'm guessing the user and pass edited there should be the user and pass set on the second machine (10.66.0.2)
- "chmod 777 /initialConfiguration.sh" should be changed to "chmod 777 initialConfiguration.sh" in the docs
- "/bin/bash /initialConfiguration.sh" should be changed to "/bin/bash initialConfiguration.sh" in the docs
- running initialConfiguration.sh ends up with error "sed: can't read /etc/netplan/01-netcfg.yaml: No such file or directory"
- adding a system from the web.fluffi ends up in 502 error bad gateway error. Also is not clear if the hostname of the second machine needs to have ".fluffi" suffix as when adding a new system there is a message "The extension .fluffi to reach the system is set automatically."

**Comment by TomSie** [comment]
Very good points. Could you please have a look at https://github.com/siemens/fluffi/tree/usage_docs_for_system_adding ? Does this answer your questions? If not: please let me know what is missing.

**Comment by joyride9999** [comment]
> Very good points. Could you please have a look at https://github.com/siemens/fluffi/tree/usage_docs_for_system_adding ? Does this answer your questions? If not: please let me know what is missing.

yes, ty!
