### ISSUE TITLE
can we somehow allow an anonymously writable ftp root?

### ISSUE THREAD

**Issue by p0wer0xff** [siemens/fluffi#125]
otherwise we cannot use ftp to create new subdirectories and files in root, as mentioned in #103

**Comment by TomSie** [comment]
now that the documentation is updated, do we still need this?

**Comment by p0wer0xff** [comment]
probably not for our use case, but it vexes me that v(ery)s(tupid)ftpd does not seem to mind `allow_writeable_chroot=YES` at all.

also, if someone wants to extend FLUFFI and needs new directories, it's just inconvenient not to have a writable root.

**Comment by TomSie** [comment]
Given that there is no easy fix, and the need for this feature is minimal, I would close this issue as won't fix for now. Is that fine with you?

**Comment by p0wer0xff** [comment]
So, we are running vsftpd version 3.0.3
![image](https://user-images.githubusercontent.com/55484502/79566708-4eeede00-80b3-11ea-8764-4693a800b8ac.png)
from the ubuntu repositories for 18.04 as per [Dockerfile](https://github.com/siemens/fluffi/blob/master/srv/fluffi/ftp/Dockerfile#L14) to which the sources are located [here](https://packages.ubuntu.com/bionic/vsftpd)

My initial gut feeling was that the packaging people at ubuntu/debian might have disabled the option for security, but the only patch that touches the subject is `debian/patches/0060-seccomp_sandbox.patch` which sets the default value at compile time to `tunable_allow_writeable_chroot = 0;`

because in several search results on google there are inconsistencies concerning what the config option is supposed to be called, looking into the vsftpd source, we find the correct spelling of the option in parseconf.c
```
109   { "allow_writeable_chroot", &tunable_allow_writeable_chroot },
```

so it is actually set when present in the config file. Next, we find the error message in secutil.c:
```
132   /* Misconfiguration check: don't ever chroot() to a directory writable by                                                                                                                                     
133    * the current user.                                                                                                                                                                                          
134    */                                                                                                                                                                                                           
135   if ((options & VSF_SECUTIL_OPTION_CHROOT) &&                                                                                                                                                                  
136       !(options & VSF_SECUTIL_OPTION_ALLOW_WRITEABLE_ROOT))                                                                                                                                                     
137   {                                                                                                                                                                                                             
138     if (vsf_sysutil_write_access("/"))                                                                                                                                                                          
139     {                                                                                                                                                                                                           
140       die("vsftpd: refusing to run with writable root inside chroot()");                                                                                                                                        
141     }                                                                                                                                                                                                           
142   }
```
which leads us back to twoprocess.c:
```
452     if (!was_anon && tunable_allow_writeable_chroot)                                                                                                                                                            
453     {                                                                                                                                                                                                           
454       secutil_option |= VSF_SECUTIL_OPTION_ALLOW_WRITEABLE_ROOT;                                                                                                                                                
455     }
```
So we learn a seemingly common misunderstanding (looking at the dozens of search results on the topic and no working answer), namely that vsftpd does not allow writable chroot **at all** when using **anonymous login** and the chrooting security mechanism, no matter if the config option is set or not. The only conceivable way to reach our goal here might be to disable the chrooting behavior, but that might entail more investigation into consequences.

With these results I'm closing this as _wontfix_, though I do so begrudgingly.

**Comment by p0wer0xff** [comment]
oh, btw, @maverickwoo you might be interested in this, since you originally brought it to my attention.
