### ISSUE TITLE
Missing dependencies info "smbclient"

### ISSUE THREAD

**Issue by joyride9999** [siemens/fluffi#127]
In usage section, there is :
"smbclient '//smb.fluffi/install' -c 'cd initial; get MAC2Host.csv; get initialConfiguration.sh' -U"

At least on ubuntu18.04 desktop, this is not installed by default ... anyway because of the ip changing, and dns resolving stuff by the time i arrived to this part the machine had no internet so had to remake it again with inet :)

_Originally posted by @joyride9999 in https://github.com/siemens/fluffi/issues/112#issuecomment-607807025_

**Comment by TomSie** [comment]
Apparently, there are multiple problems:
1) We need to document how to set up a local packet mirror (apt.fluffi)
2) The usage.md needs to mention that 
- the system to be added needs to be able to reach a repository (either the real one, or a mirror)
- smbclient needs to be installed
3) The documentation to crate ubuntu images (ubuntu.md) needs to be updated to
- Set the packet mirror to apt.fluffi
- Include smbclient in the image

**Comment by TomSie** [comment]
3) is done with https://github.com/siemens/fluffi/commit/c45b4479396a098df83c45faf537786f22b36fb0

**Comment by TomSie** [comment]
1. is done with https://github.com/siemens/fluffi/commit/cf1f3e4fd69b85c65341e5e49e1c0747d8d39f92

**Comment by TomSie** [comment]
2. is done with https://github.com/siemens/fluffi/commit/8bce736a186d8eb157d9d4d46ee675cf4b1f4418
