### ISSUE TITLE
building on linux RAM

### ISSUE THREAD

**Issue by joyride9999** [siemens/fluffi#128]
In the section for compiling fluffi on linux it say "please install/allocate at least 6 GB of RAM", however for safety reasons i think should also recommend setting the swap file of 8GB.
Saying this because having ~8gb RAM for the machine and 4 gb swap, it may happen that at some point will run OOM and will crash when compiling!

**Comment by p0wer0xff** [comment]
Without knowing the full details of your compile run and environment this is hard to reproduce. When following the new guide (please note that the 6GB you cite are just an example - the [actual amount of memory](https://github.com/siemens/fluffi/blame/refactor-deployment-and-doc/getting_started.md#L61) depends on the number of jobs, which scales with the number of allocated CPU cores) and after applying the patches in #124 (where we fix the memory issue with make -j) it works without using swap in my tests.

**Comment by joyride9999** [comment]
Had 3 cpu cores and 8gb allocated ram (on a vbox machine) ... this is why i was saying that its safer to mention/recommend also having a bigger swap file ...
Also i was on the refactor-deployment-and-doc branch

**Comment by TomSie** [comment]
is there still an action item here or can we close this issue?
