### ISSUE TITLE
Deploy SUT/Dependency->Select Package doesn't work for Linux Machines

### ISSUE THREAD

**Issue by vinamrabhatia** [siemens/fluffi#131]
With the master at following [commit](https://github.com/siemens/fluffi/tree/434131627a901e9503d365e704a7d963516c168d), http://web.fluffi:8880/systems shows multiple groups: windows, linux and odroids.
Clicking on any of the machines in Linux group takes us to a tab which has 4 options. (I guess the 4th option doesn't exist anymore as per the latest master).

For 3] `Deplot SUT/Dependency`,  'Deploy' option in 'Select Fuzzjob:' doesn't work. 

I am also attaching the docker-compose logs when I press the button:

> fluffiweb_1  | Traceback (most recent call last):
> fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
> fluffiweb_1  |     return self.wsgi_app(environ, start_response)
> fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
> fluffiweb_1  |     response = self.handle_exception(e)
> fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
> fluffiweb_1  |     reraise(exc_type, exc_value, tb)
> fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
> fluffiweb_1  |     raise value
> fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
> fluffiweb_1  |     response = self.full_dispatch_request()
> fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
> fluffiweb_1  |     rv = self.handle_user_exception(e)
> fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
> fluffiweb_1  |     reraise(exc_type, exc_value, tb)
> fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
> fluffiweb_1  |     raise value
> fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
> fluffiweb_1  |     rv = self.dispatch_request()
> fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
> fluffiweb_1  |     return self.view_functions[rule.endpoint](**req.view_args)
> fluffiweb_1  |   File "./app/views.py", line 1511, in viewInstallFuzzjobPackage
> fluffiweb_1  |     name=selectedFuzzJob).join(models.FuzzjobDeploymentPackages).filter(
> fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2243, in join
> fluffiweb_1  |     from_joinpoint=from_joinpoint,
> fluffiweb_1  |   File "<string>", line 2, in _join
> fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/base.py", line 220, in generate
> fluffiweb_1  |     fn(self, *args[1:], **kw)
> fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2422, in _join
> fluffiweb_1  |     left, right, onclause, prop, create_aliases, outerjoin, full
> fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2445, in _join_left_to_right
> fluffiweb_1  |     ) = self._join_determine_implicit_left_side(left, right, onclause)
> fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2578, in _join_determine_implicit_left_side
> fluffiweb_1  |     "Can't determine which FROM clause to join "
> fluffiweb_1  | sqlalchemy.exc.InvalidRequestError: Can't determine which FROM clause to join from, there are multiple FROMS which can join to this entity. Try adding an explicit ON clause to help resolve the ambiguity.
> fluffiweb_1  | [pid: 16|app: 0|req: 137/455] 10.180.62.198 () {50 vars in 1073 bytes} [Mon Apr  6 20:18:04 2020] POST /systems/view/fluffi-0228-Linux1/deployFuzzPackage => generated 0 bytes in 8 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
> fluffiweb_1  | 2020/04/06 20:18:04 [error] 12#12: *875 upstream prematurely closed connection while reading response header from upstream, client: 10.180.62.198, server: , request: "POST /systems/view/fluffi-0228-Linux1/deployFuzzPackage HTTP/1.1", upstream: "uwsgi://unix:///tmp/uwsgi.sock:", host: "web.fluffi:8880", referrer: "http://web.fluffi:8880/systems/view/fluffi-0228-Linux1/linux"
> fluffiweb_1  | 10.180.62.198 - - [06/Apr/2020:20:18:04 -0400] "POST /systems/view/fluffi-0228-Linux1/deployFuzzPackage HTTP/1.1" 502 173 "http://web.fluffi:8880/systems/view/fluffi-0228-Linux1/linux" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0" "-"

**Comment by p0wer0xff** [comment]
@jones718 - could you have a look at this please?

**Comment by jones718** [comment]
I fixed the sqlalchemy error in pull request #133. I will investigate in the deployment on web.fluffi a bit more to test whether there are other errors related to this.
