### ISSUE TITLE
Fuzzjobs sync systems failed

### ISSUE THREAD

**Issue by joyride9999** [siemens/fluffi#137]
I keep getting the error 
"Sync systems failed!

Something went wrong at the inital synchronization between PoleMarch and the database. Pleasy retry!"

![VirtualBox_ubuntu 18 04 main_15_04_2020_13_52_33](https://user-images.githubusercontent.com/26308356/79329409-6ea1cd00-7f20-11ea-9b08-61ba41c09d93.png)

**Comment by p4cx** [comment]
I can see the Polemarch tabs on the screenshot: Is it available at "pole.fluffi:8888/"? When I start Webgui and Polemarch, everything works. It almost looks like the Webgui is not reaching Polemarch.

**Comment by joyride9999** [comment]
yes it is available, will try to get a log if i see the error again
