### ISSUE TITLE
missing documentation on how to start a fuzzjob

### ISSUE THREAD

**Issue by joyride9999** [siemens/fluffi#140]
Its needed to add information on how to actually start a fuzzjob :)
Would help a bit also if a small description is also added regarding on what the 4 steps are doing:
1) initial setup
2) deploy fluffi 
3) deploy SUT/Dependency
4) configure instances
And also some description regarding the parameters in each tab.

**Comment by TomSie** [comment]
4) is already documented in section 4) of usage.md
