### ISSUE TITLE
deploy fluffi task failed 

### ISSUE THREAD

**Issue by joyride9999** [siemens/fluffi#143]
```
TASK [deployment-windows-fluffi : Fetch FLUFFI from "ftp://ftp.fluffi/fluffi/windows/x64/fluffi.zip"] ***
fatal: [batrix3]: FAILED! => {"changed": false, "dest": "C:\\FLUFFI\\x64\\fluffi.zip", "elapsed": 0, "msg": "Error requesting 'ftp://ftp.fluffi/fluffi/windows/x64/fluffi.zip'. The remote server returned an error: (550) File unavailable (e.g., file not found, no access).", "status_code": 550, "url": "ftp://ftp.fluffi/fluffi/windows/x64/fluffi.zip"}

PLAY RECAP *********************************************************************
batrix3                    : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by p0wer0xff** [comment]
Does the file exist? You need to create the deployment file by doing a compile run of FLUFFI with the DEPLOY_TO_FTP parameter.

**Comment by joyride9999** [comment]
no, i forgot about this step :D

**Comment by joyride9999** [comment]
seems that for windows i need to build them on windows and then manually copy the zip files? is there  another way? 
i'm guessing running buildAll.bat -DEPLOY_TO_FTP TRUE on windows will work only if the windows build machine is on the same network.
Maybe a mention of this will help also in the guideline!

**Comment by p0wer0xff** [comment]
yes exactly, if you have the build machine on the same network, this switch will create the deployment file as well.
