### ISSUE TITLE
update copyright header

### ISSUE THREAD

**Issue by TomSie** [siemens/fluffi#145]
currently all files start with 
> Copyright 2017-2019 Siemens AG

This needs to be changed to 

> Copyright 2017-2020 Siemens AG

**Comment by p0wer0xff** [comment]
Suggestion: If we need to touch all of the files anyway, we could try to work our way to a more standardized header format. Currently the three paragraphs of the MIT license are one line each, a more standard way to do it would be to limit line length to something like 80 characters. Formatting examples can be seen [here](https://github.com/jquery/jquery/blob/master/LICENSE.txt) and [here](https://github.com/nodejs/node/blob/master/LICENSE). 

Implementation wise we can probably modify the existing header update script.

**Comment by TomSie** [comment]
disadvantage: our update authors script will have a strong bias towards the person that committed the license

**Comment by p4cx** [comment]
What if we create a new github user to update the authors and header in general and add his name as an exception so that it doesn't appear in the header?

**Comment by TomSie** [comment]
TeamFLUFFI ?

**Comment by p0wer0xff** [comment]
I like that idea. Let's use "Team FLUFFI" (with a space), because that would be consistent with what I used when porting the repo to github, though I do not know if any lines with that author remain at all after fixing authorship in the first commits here.

**Comment by TomSie** [comment]
@jones718 could you please 
1) Write a script that automatically updates the license headers for all possible comment types
- Set end date correctly
- Use different line formating
2) Update our Authors script to ignore all lines written by "Team FLUFFI"
