### ISSUE TITLE
Windows shortcuts on runner after deploy of fluffi are wrong

### ISSUE THREAD

**Issue by joyride9999** [siemens/fluffi#148]
After deploy fluffi action, the shortcuts are created with wrong path.
Also the path seems to be the only difference between "disk" and "ram" shortcuts

![VirtualBox_MSEdge - Win10_17_04_2020_14_25_38](https://user-images.githubusercontent.com/26308356/79564480-6af47e80-80b7-11ea-9276-5193fa6a09ec.png)

**Comment by TomSie** [comment]
As far as I can see, the ramdisk (F) was not created. 
Two questions:
Do the Disk shortcuts work?
Did you run the "initialsetup" step?

**Comment by joyride9999** [comment]
yes the disk shortcuts start/work
and i run the initial setup step

**Comment by TomSie** [comment]
Did you replace the files in srv\fluffi\data\ftp\files\initial\windows\ansible\ImDisk with actual files, as documented in the getting_started.md ?

**Comment by joyride9999** [comment]
Something went wrong when i took lmdisk binary as it had 0 bytes.  I did again the initial setup step, but now its stuck with status "DELAY"!

**Comment by TomSie** [comment]
Are you aware, that the binaries in the repository are just placeholders that need to be replaced with the actual files?

**Comment by joyride9999** [comment]
was saying that i remember  replacing them, but when i looked again the lmdisk file had 0 bytes :), so something went , so probably copy paste didnt work for some reason :)

**Comment by TomSie** [comment]
is there an action item left here or should we close this issue?

**Comment by joyride9999** [comment]
well there is still a question, now the initial setup remains with the status "DELAY" ... should i redo the windows agent? or it should be able to "redeploy"
Also initially when i ran the deploy step ..it finished with status OK even though lmdisk file was not the real binary...  wouldn't an error message be more appropriate ...eg. for this case "can't create ram disk" or something similar!

**Comment by TomSie** [comment]
redeploying the initial setup step should be fine.

DELAY is a polemarch specific state. It means "right now I cannot perform the task you gave me". Usually this happens if 

-  The initial sync step failed (status of the FLUFFI project is not "OK")
- There is currently another task going on

I will create a new issue on the problem that initial setup succeeds although the binaries are invalid.
