### ISSUE TITLE
Usage and starting agents

### ISSUE THREAD

**Issue by joyride9999** [siemens/fluffi#149]
In the docs it is mentioned "Alternatively, you can connect to the system directly (SSH, RDP), and start the agents there." ... 
Using only the interface LM, TR, TG and TE did not start automatically after deployment of fluffi ... so it seems to me that they can be started only by remote ssh/rdp

**Comment by TomSie** [comment]
We need to document how the agent starter works, and what can be done manually (e.g. when debugging errors)
