### ISSUE TITLE
Order to start apps on agents

### ISSUE THREAD

**Issue by joyride9999** [siemens/fluffi#150]
Is not really clear in what order LM, T* should be started ... and it seems one agent is waiting for another
![VirtualBox_MSEdge - Win10_17_04_2020_14_36_02](https://user-images.githubusercontent.com/26308356/79565165-ca9f5980-80b8-11ea-9d1b-90bf7916dc85.png)

**Comment by TomSie** [comment]
Actually, they are waiting for you to assign them on a fuzzjob. 

This is done automatically, if the agents are started by the agentstarter. 

If you start the agents manually, you have to assign them to a fuzzjob in the Location page
