### ISSUE TITLE
Initial setup succeeds with stub binaries

### ISSUE THREAD

**Issue by TomSie** [siemens/fluffi#151]
Appatently, the initial setup step on windows succeeds in environments in which the binaries in /srv/fluffi/data/ftp/files/initial/windows/ansible were not replaced with actual files. 

Please modify the /srv/fluffi/data/polenext/projects/1/roles/initial-windows* tasks to fail when the downloaded binaries are invalid (e.g. to small)

**Comment by p0wer0xff** [comment]
we could run `file` against the "binaries" and see if they are text files or not

**Comment by TomSie** [comment]
wouldn't work on Windows. Yes, we could do something fancy here, but i would stick to file size check for now.
