### ISSUE TITLE
deploy fluffi fails with "connection types on this machine is set to Public"

### ISSUE THREAD

**Issue by joyride9999** [siemens/fluffi#154]
PLAY [windows] *****************************************************************

TASK [Gathering Facts] *********************************************************
ok: [batrix3]

TASK [initial-windows-Timezone : Set timezone to 'Romance Standard Time' (GMT+01:00)] ***
ok: [batrix3]

TASK [initial-windows-GFlags : Ensure source directory exists] *****************
ok: [batrix3]

TASK [initial-windows-GFlags : Fetch GFlag zip file "ftp://ftp.fluffi/initial/windows/ansible/GFlags/GFlags.zip"] ***
changed: [batrix3]

TASK [initial-windows-GFlags : Unzip GFlags] ***********************************
changed: [batrix3]

TASK [initial-windows-PrepareEnvironment : Create a FLUFFI directory] **********
ok: [batrix3]

TASK [initial-windows-PrepareEnvironment : Set ACL for C:\FLUFFI] **************
ok: [batrix3]

TASK [initial-windows-PrepareEnvironment : Set AllowUnencrypted to True] *******
fatal: [batrix3]: FAILED! => {"changed": true, "cmd": "Set-Item -Path WSMan:\\localhost\\Service\\AllowUnencrypted -Value $true", "delta": "0:00:03.234031", "end": "2020-04-16 09:33:04.872752", "msg": "non-zero return code", "rc": 1, "start": "2020-04-16 09:33:01.638721", "stderr": "Set-Item : WinRM firewall exception will not work since one of the network connection types on this machine is set to \r\nPublic. Change the network connection type to either Domain or Private and try again. \r\nAt line:1 char:65\r\n+ ... ing $false; Set-Item -Path WSMan:\\localhost\\Service\\AllowUnencrypted  ...\r\n+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [Set-Item], InvalidOperationException\r\n    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.SetItemCommand", "stderr_lines": ["Set-Item : WinRM firewall exception will not work since one of the network connection types on this machine is set to ", "Public. Change the network connection type to either Domain or Private and try again. ", "At line:1 char:65", "+ ... ing $false; Set-Item -Path WSMan:\\localhost\\Service\\AllowUnencrypted  ...", "+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "    + CategoryInfo          : NotSpecified: (:) [Set-Item], InvalidOperationException", "    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.SetItemCommand"], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
batrix3                    : ok=7    changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by TomSie** [comment]
Apparently, we need to add a step in the srv/fluffi/data/polenext/projects/1/roles/initial-windows-PrepareEnvironment/tasks/main.yml to make sure all network adapters are set to 'Private'. I think a good way to do so is documented at http://www.hurryupandwait.io/blog/fixing-winrm-firewall-exception-rule-not-working-when-internet-connection-type-is-set-to-public

Please note: Although there seems to be an easy way for windows 8 and up, we should use the solution that also works for Windows 7

**Comment by joyride9999** [comment]
Please note that it seems there is also a problem with polemarch reporting system... although some tasks had errors they are reported as OK

**Comment by TomSie** [comment]
Imho this works as intended: The first 7 tasks passed (ok/changed), and the 8th task failed. 
At the bottom a summary is displayed
`batrix3 : ok=7 changed=2 unreachable=0 failed=1 skipped=0 rescued=0 ignored=0`

**Comment by joyride9999** [comment]
:)) well it creates a pretty confusing situation because you expect that the task is ok as you see first the status without clicking on the details output, and that say its ok but its actually not. 
A normal behaviour would be one task failed -> the entire status should be "ERROR" or at least this is how i would see it :)

![Capture](https://user-images.githubusercontent.com/26308356/79967017-f2b30200-8496-11ea-95e1-f44d6f524704.PNG)
![image](https://user-images.githubusercontent.com/26308356/79967595-b3d17c00-8497-11ea-94eb-7892bc8abd66.png)
