### ISSUE TITLE
ERROR: for fluffigm  Cannot start service fluffigm: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"./GlobalManager\": stat ./GlobalManager: no such file or directory": unknown"

### ISSUE THREAD

**Issue by satyendra22** [siemens/fluffi#157]
While starting container getting error as  
> "ERROR: for fluffigm  Cannot start service fluffigm: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"./GlobalManager\": stat ./GlobalManager: no such file or directory": unknown"

`ubuntu@ubuntu1804:~$ cd FLUFFI/srv/fluffi/
ubuntu@ubuntu1804:~/FLUFFI/srv/fluffi$ sudo docker-compose -f /srv/fluffi/docker-compose.yaml up -d --force-recreate
Removing fluffi_fluffigm_1
Recreating fluffi_mon_1 ... 
Recreating fluffi_polenext_1 ... 
Recreating fluffi_fluffiweb_1 ... 
Recreating fluffi_dnsmasq_1               ... done
Recreating fluffi_polenext_1              ... done
Recreating fluffi_mon_1                   ... done
Recreating fluffi_smb_1       ... 
Recreating fluffi_fluffiweb_1             ... done
Recreating 81e2bb49e3a6_fluffi_fluffigm_1 ... error
Recreating fluffi_dashsync_1              ... done
Recreating fluffi_grasync_1               ... done
Recreating fluffi_smb_1                   ... done
Recreating fluffi_ftp_1                   ... done
 unkRecreating fluffi_ntp_1                   ... done

ERROR: for fluffigm  Cannot start service fluffigm: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"./GlobalManager\": stat ./GlobalManager: no such file or directory": unknown
ERROR: Encountered errors while bringing up the project.
ubuntu@ubuntu1804:~/FLUFFI/srv/fluffi$ cd data/fluffigm/
ubuntu@ubuntu1804:~/FLUFFI/srv/fluffi/data/fluffigm$ ls
GlobalManager  libmariadb.so.3  libsharedmemipc.so  libzmq.so.5
ubuntu@ubuntu1804:~/FLUFFI/srv/fluffi/data/fluffigm$ nano GlobalManager 
ubuntu@ubuntu1804:~/FLUFFI/srv/fluffi/data/fluffigm$ `

As per doc I have already added GlobalManager components into /srv/fluffi/data/fluffigm/

**Comment by TomSie** [comment]
did you perform all the steps documented in the getting_started.md? In particular, did you run `sudo chmod -R +x /srv/fluffi/data/fluffigm`?

**Comment by TomSie** [comment]
Also: Could you show us the output of `file /srv/fluffi/data/fluffigm/GlobalManager` ?

**Comment by satyendra22** [comment]
@TomSie i re-install complete setup and error is gone ..Thx
