### ISSUE TITLE
Add task schedule to run lm script at start up  failed

### ISSUE THREAD

**Issue by joyride9999** [siemens/fluffi#158]
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and 
make sure become_method is 'sudo' (default). This feature will be removed in 
version 2.9. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.

PLAY [linux, odroids] **********************************************************
skipping: no hosts matched

PLAY [windows] *****************************************************************

TASK [Gathering Facts] *********************************************************
ok: [batrixwin]

TASK [initial-windows-Timezone : Set timezone to 'Romance Standard Time' (GMT+01:00)] ***
ok: [batrixwin]

TASK [initial-windows-GFlags : Ensure source directory exists] *****************
ok: [batrixwin]

TASK [initial-windows-GFlags : Fetch GFlag zip file "ftp://ftp.fluffi/initial/windows/ansible/GFlags/GFlags.zip"] ***
changed: [batrixwin]

TASK [initial-windows-GFlags : Unzip GFlags] ***********************************
changed: [batrixwin]

TASK [initial-windows-PrepareEnvironment : Create a FLUFFI directory] **********
ok: [batrixwin]

TASK [initial-windows-PrepareEnvironment : Set ACL for C:\FLUFFI] **************
ok: [batrixwin]

TASK [initial-windows-PrepareEnvironment : Set AllowUnencrypted to True] *******
changed: [batrixwin]

TASK [initial-windows-GroupPolicy : Fetch LGPO from "ftp://ftp.fluffi/initial/windows/ansible/LGPO/LGPO.exe"] ***
changed: [batrixwin]

TASK [initial-windows-GroupPolicy : Copy registry.txt to remote machine via template] ***
changed: [batrixwin]

TASK [initial-windows-GroupPolicy : Execute LGPO.exe to generate group policy registry.pol] ***
changed: [batrixwin]

TASK [initial-windows-GroupPolicy : Execute LGPO.exe to apply group policy registry.pol] ***
changed: [batrixwin]

TASK [initial-windows-pagefile : Disabling pagefiles on windows] ***************
changed: [batrixwin]

TASK [initial-windows-Imdisk : Check architecture for x86 installer] ***********
skipping: [batrixwin]

TASK [initial-windows-Imdisk : Fetch ImDisk installer from "ftp://ftp.fluffi/initial/windows/ansible/ImDisk/ImDiskTk-x64.exe"] ***
changed: [batrixwin]

TASK [initial-windows-Imdisk : Install imdisk by executing ImDiskTk-x64.exe] ***
changed: [batrixwin]

TASK [initial-windows-Imdisk : Create new ramdisk] *****************************
changed: [batrixwin]

TASK [initial-windows-Imdisk : Ensure startup script directory exists] *********
changed: [batrixwin]

TASK [initial-windows-Imdisk : Copy startup script to machine] *****************
changed: [batrixwin]

TASK [initial-windows-Imdisk : Add task schedule to run script at start up] ****
fatal: [batrixwin]: FAILED! => {"changed": true, "msg": "failed to modify scheduled task: (17,8):UserId:"}

RUNNING HANDLER [initial-windows-GroupPolicy : Ensure Windows NTP service is running] ***

RUNNING HANDLER [initial-windows-GroupPolicy : Force Windows NTP time sync] ****

PLAY RECAP *********************************************************************
batrixwin                  : ok=18   changed=13   unreachable=0    failed=1    skipped=1    rescued=0    ignored=0

**Comment by TomSie** [comment]
1) is the bug reproducible?
2) is there a manageFluffiRamdisk.bat in %SYSTEMROOT%\System32\GroupPolicy\User\Scripts\Logon ?

**Comment by joyride9999** [comment]
1) yes 
```
TASK [initial-windows-Imdisk : Add task schedule to run script at start up] ****
fatal: [batrixwin]: FAILED! => {"changed": false, "msg": "failed to modify scheduled task: (17,8):UserId:"}
```
2) yes the script is there

**Comment by TomSie** [comment]
could it be that the user running the ansible task does not have the necessary privileges? We use the local "Administrator" in our setup

**Comment by joyride9999** [comment]
same here, its the same user and its in the administrators group

**Comment by TomSie** [comment]
Hmm ... It says failed to update. Have you checked if there already is a Windows scheduled task called syncFluffiToRAM?

Btw: We are talking about the last entry in
srv/fluffi/data/polenext/projects/1/roles/initial-windows-Imdisk/tasks/main.yml
maybe you can play a little bit around with that and try to debug it?

**Comment by joyride9999** [comment]
the task is there !
 
sure ill give it a look and try to figure out whats happening

**Comment by joyride9999** [comment]
Is there a specific version of imdisk that should be there? (i have 2.0.10.49)
1) at first glance seems that the task is not running at reboot 
2) F: ramdrive is not there anymore, running the task manually ends up in requesting me to format it 
![VirtualBox_MSEdge - Win10_23_04_2020_10_19_29](https://user-images.githubusercontent.com/26308356/80070707-0ff5d800-854c-11ea-8b63-bc6e613c2184.png)

**Comment by TomSie** [comment]
maybe it's better to reinstall the agent system and run the task on a fresh installation. All of these issues look strange.

**Comment by joyride9999** [comment]
will do that ,
regarding the task it looks like it failed to add the trigger action (as there is nothing in that tab)
![VirtualBox_MSEdge - Win10_23_04_2020_10_29_24](https://user-images.githubusercontent.com/26308356/80071462-57309880-854d-11ea-8852-5a4de3b98dea.png)
![VirtualBox_MSEdge - Win10_23_04_2020_10_26_36](https://user-images.githubusercontent.com/26308356/80071472-5d267980-854d-11ea-9389-6bfa093493e2.png)

**Comment by joyride9999** [comment]
closing this as it seems as i couldnt simulate on another machine
