### ISSUE TITLE
Fetch Rest-Instance-Starter-Autostart failed

### ISSUE THREAD

**Issue by joyride9999** [siemens/fluffi#159]
[WARNING]: While constructing a mapping from /usr/local/lib/python3.6/dist-
packages/polemarch/projects/1/roles/general-windows-
syncToRamdisk/tasks/main.yml, line 25, column 3, found a duplicate dict key
(win_file). Using last defined value only.

[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and 
make sure become_method is 'sudo' (default). This feature will be removed in 
version 2.9. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.

PLAY [windows] *****************************************************************

TASK [Gathering Facts] *********************************************************
ok: [batrixwin]

TASK [deployment-windows-fluffi : Ensure directory exists] *********************
changed: [batrixwin]

TASK [deployment-windows-fluffi : Fetch FLUFFI from "ftp://ftp.fluffi/fluffi/windows/x64/fluffi.zip"] ***
changed: [batrixwin]

TASK [deployment-windows-fluffi : Unzip FLUFFI to persistent C] ****************
changed: [batrixwin]

TASK [deployment-windows-fluffi : Parse location to host] **********************
ok: [batrixwin] => (item={'key': 'batrixwin', 'value': 'FLUFFI'})

TASK [deployment-windows-fluffi : Create persistent shortcuts on desktop] ******
changed: [batrixwin] => (item={'key': 'TR', 'value': 'TestcaseRunner'})
changed: [batrixwin] => (item={'key': 'TG', 'value': 'TestcaseGenerator'})
changed: [batrixwin] => (item={'key': 'TE', 'value': 'TestcaseEvaluator'})
changed: [batrixwin] => (item={'key': 'LM', 'value': 'LocalManager'})

TASK [deployment-windows-fluffi : Create ramdisk shortcuts on desktop] *********
changed: [batrixwin] => (item={'key': 'TR', 'value': 'TestcaseRunner'})
changed: [batrixwin] => (item={'key': 'TG', 'value': 'TestcaseGenerator'})
changed: [batrixwin] => (item={'key': 'TE', 'value': 'TestcaseEvaluator'})
changed: [batrixwin] => (item={'key': 'LM', 'value': 'LocalManager'})

TASK [general-windows-syncToRamdisk : Obtain information about ramdisk] ********
ok: [batrixwin]

TASK [general-windows-syncToRamdisk : Check existence] *************************
skipping: [batrixwin]

TASK [general-windows-syncToRamdisk : Delete existing files on ramdisk (x64)] ***
ok: [batrixwin]

TASK [general-windows-syncToRamdisk : Ensure directories exists] ***************
changed: [batrixwin]

TASK [general-windows-syncToRamdisk : Execute copy command for x64] ************
changed: [batrixwin]

TASK [general-windows-syncToRamdisk : Execute copy command for x64/dynamorio] ***
changed: [batrixwin]

TASK [general-windows-syncToRamdisk : Execute copy command for x86] ************
changed: [batrixwin]

TASK [general-windows-syncToRamdisk : Execute copy command for x86/dynamorio] ***
changed: [batrixwin]

TASK [initial-windows-deployRestInstanceStarter : Set file path to fetch] ******
ok: [batrixwin]

TASK [initial-windows-deployRestInstanceStarter : Create a FLUFFI directory] ***
changed: [batrixwin]

TASK [initial-windows-deployRestInstanceStarter : Fetch Rest-Instance-Starter from "ftp://ftp.fluffi/restStarter/main.py"] ***
changed: [batrixwin]

TASK [initial-windows-deployRestInstanceStarter : Fetch Rest-Instance-Starter-Autostart from "ftp://ftp.fluffi/restStarter/restInstanceAutostart.bat"] ***
fatal: [batrixwin]: FAILED! => {"changed": false, "dest": "C:\\Users\\Administrator\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\\restInstanceAutostart.bat", "elapsed": 0, "msg": "The path 'C:\\Users\\Administrator\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup' does not exist for destination 'C:\\Users\\Administrator\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\\restInstanceAutostart.bat', or is not visible to the current user.  Ensure download destination folder exists (perhaps using win_file state=directory) before win_get_url runs.", "url": "ftp://ftp.fluffi/restStarter/restInstanceAutostart.bat"}

PLAY RECAP *********************************************************************
batrixwin                  : ok=17   changed=12   unreachable=0    failed=1    skipped=1    rescued=0    ignored=0

**Comment by TomSie** [comment]
1) Is that a Windows 7 machine?
2) Is the bug reproducible?

We hat the problem that on Windows 7 machines sometimes the ftp download failed.

**Comment by joyride9999** [comment]
1) no, its win 10 enterprise (eval) 1809
2) now it does not get to that step, it fails earlier
```
TASK [general-windows-syncToRamdisk : Check existence] *************************
fatal: [batrixwin]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}
```

**Comment by TomSie** [comment]
So this time it looks as if the ramdisk is not there? Maybe this is connected to #158 ?

**Comment by joyride9999** [comment]
maybe that's why it fails, because the ramdisk is already there and can't create it again..therefore it does not reach the step mentionen initially in the bug
