### ISSUE TITLE
win10 enterprise 18362 & winrm

### ISSUE THREAD

**Issue by joyride9999** [siemens/fluffi#166]
Seems that when using a newer version of windows , ansible is not able to connect through winrm ( firewall is off)
Winrm is configured as in prtscreen... should something else be done?
![winrm](https://user-images.githubusercontent.com/26308356/80352717-f8d12600-887c-11ea-87f4-d4664b70aa9b.png)

Patch "Windows6.1-KB2819745-x64-MultiPkg.msu" is for win 7 so it will fail on win 10.
Is there a constriaint that for windows should be used only win7?

Overall doing a test in python
```
import winrm

s = winrm.Session('win10.fluffi', auth=('user', 'user'))
r = s.run_cmd('ipconfig', ['/all'])
```
ends up with this error 
```
 raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='win10.fluffi', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d7d874610>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by TomSie** [comment]
did you run the initialConfiguration.bat?

**Comment by joyride9999** [comment]
yes, after running the script file it did not work, and then start in looking why and then checking the winrm service

**Comment by TomSie** [comment]
we use Windows 10 ourselves. Maybe the problem is related to the network adapters not being set to "private" network?

**Comment by joyride9999** [comment]
they are also set to private

**Comment by TomSie** [comment]
is the port reachable? What does nmap say?

**Comment by joyride9999** [comment]
no is not reachable...
```
Host is up (0.00034s latency).
rDNS record for 10.66.1.221: WIN10.fluffi

PORT     STATE  SERVICE
5985/tcp closed wsman
```
however running winrm enum winrm/config/listener
```
winrm enum winrm/config/listener
Listener [Source="GPO"]
    Address = *
    Transport = HTTP
    Port = 5985
    Hostname
    Enabled = true
    URLPrefix = wsman
    CertificateThumbprint
    ListeningOn = null

Listener [Source="Compatibility"]
    Address = *
    Transport = HTTP
    Port = 80
    Hostname
    Enabled = true
    URLPrefix = wsman
    CertificateThumbprint
    ListeningOn = null

Listener [Source="Compatibility"]
    Address = *
    Transport = HTTPS
    Port = 443
    Hostname = WIN10
    Enabled = true
    URLPrefix = wsman
    CertificateThumbprint
    ListeningOn = null
```
so im guessing listeningon = null is the problem here

**Comment by joyride9999** [comment]
it should look like that 
```
ListeningOn = 10.66.1.221, 127.0.0.1, ::1, fe80::b408:9bb3:e3de:2f5b%7
```
I will do a second test with a new machine and run each command manually and see if it fails again and where

**Comment by joyride9999** [comment]
It looks like its working now, can't really bring it to the previous state
