### ISSUE TITLE
Agents not starting automatically :/

### ISSUE THREAD

**Issue by joyride9999** [siemens/fluffi#169]
After waiting for some time , seems that the agents wont start automatically...
What should i check for next ?

1)Scheduled task is there
2) manageFluffiRamdisk - is there
3) ramdrive is created
4) initial setup and deploy fluffi run ok
5) instances were created

![image](https://user-images.githubusercontent.com/26308356/80459885-ba4e7080-893b-11ea-8f2c-2d87d3638f48.png)

**Comment by TomSie** [comment]
what about #168 ? Without the instance starter, instances won't start ;)

**Comment by joyride9999** [comment]
then im closing this one as it s duplicate of #168
