### ISSUE TITLE
DNS Names should be case insensitive

### ISSUE THREAD

**Issue by TomSie** [siemens/fluffi#175]
Line 357 in manageAgents.py causes problems if there are case inconsistencies in host names
```
(system == system_w) 
```

If, for example, a system was added as win101 , and the hostname is WIN101, no new agents will be assigned.

As Windows DNS seems to be case insensitive anyways, we should make the comparison case insensitive.

_Originally posted by @joyride9999 in https://github.com/siemens/fluffi/issues/173#issuecomment-623435715_

**Comment by jones718** [comment]
Fixed in pull request #179
