### ISSUE TITLE
Download of gdb crashes fails

### ISSUE THREAD

**Issue by TomSie** [siemens/fluffi#191]
Maybe, because the modules contain /.text and similar ?
![image](https://user-images.githubusercontent.com/16607413/82819410-a0ec0600-9ea0-11ea-9809-fdafbc4a15e7.png)

![image](https://user-images.githubusercontent.com/16607413/82819454-b19c7c00-9ea0-11ea-8262-42b3f7374d2e.png)

**Comment by jones718** [comment]
Fixed in pull request #198.
