### ISSUE TITLE
Information in web application: Show last added population date/time

### ISSUE THREAD

**Issue by amb42** [siemens/fluffi#200]
It would help to quickly know whether something has changed since the last time we checked the dashboard

**Comment by TomSie** [comment]
What do you think about giving numbers that changed a bold font? (e.g. number of population items?)

**Comment by amb42** [comment]
Sure, but i would still like to know when the last addition happened, also as a quick and dirty heuristic to know whether it's worth continuing the job

**Comment by TomSie** [comment]
How should it look like?

**Comment by amb42** [comment]
I would have suggested a simple row in the "General information" project overview with "Last Addition" and then the datetime on the other side. 

If that would cause too much bloat, maybe as a a mouseover on "Population"?

**Comment by jones718** [comment]
Implemented in pull request #227
