### ISSUE TITLE
Information in web application: Show coverage distribution across modules

### ISSUE THREAD

**Issue by amb42** [siemens/fluffi#202]
Show the general coverage distribution.
For bonus points, allow selecting one or more testcases and show the coverage distribution there.

This coverage information should also include information about the functions triggered, not just basic block information.

**Comment by TomSie** [comment]
If I understand you correctly, there are several tasks:

1) Show coverage per testcase
2) Show coverage per module ( for selected testcase(s) and globally)
3) Figure out how to map basic block to function (maybe by uploading something generated by ida?)
4) Show coverage for functions (for selected testcase(s) and globally)

Is that what you wish for?

**Comment by amb42** [comment]
And a fifth: Show coverage distribution across modules (pie chart or similar).
