### ISSUE TITLE
Remove option "Add target files to Fuzzjob" (make it what always happens)

### ISSUE THREAD

**Issue by TomSie** [siemens/fluffi#215]
When a new target zip file is uploaded for a fuzz job via the "upload new target" button the following should happen:
1) It should be checked if there already is a zip file for that fuzzjob
2) If there is, this file should be overwritten (note: if the uploaded file has a different name from the original file, the name of the original file needs to be kept)
3) If there is not, the uploaded file should be stored and entries in the deployment_packages and the fuzzjob_deployment_packages should be created

This is what should happen always. Therefore, the "Add target files to Fuzzjob" option should be removed.

**Comment by jones718** [comment]
Fixed in pull request #226
