### ISSUE TITLE
Web: Cannot configure number of LocalManagers

### ISSUE THREAD

**Issue by maverickwoo** [siemens/fluffi#241]
In latest `master` as of this writing (f4781fc), the guard at

https://github.com/siemens/fluffi/blob/f4781fc2a9755275dc9c11a71ee08358892f31e8/srv/fluffi/data/fluffiweb/app/controllers.py#L1365

inside `insertFormInputForConfiguredInstances` watches over every line until:

https://github.com/siemens/fluffi/blob/f4781fc2a9755275dc9c11a71ee08358892f31e8/srv/fluffi/data/fluffiweb/app/controllers.py#L1396

This leads to the backend ignoring the number of requested LMs in the posted form while returning a success message to be displayed in the browser.

**Comment by jones718** [comment]
Thanks for pointing out this bug. It will be fixed with PR #242
