### ISSUE TITLE
AVX_512 handling in DynamoRIO breaks Fluffi execution

### ISSUE THREAD

**Issue by p4cx** [siemens/fluffi#39]
On newer machines Fluffi won't start properly, because we inherited following bug of DynamoRIO:
[AVX-512 handling breaks DynamoRIO execution on Windows with full AVX-512 support](https://github.com/DynamoRIO/dynamorio/issues/3949)

The described work-around, setting `avx512_enabled` to _false_ works for now.

**Comment by TomSie** [comment]
fixed with commit 555c2f7846024102f313de9f29c566407deb2185
